# User configuration
export LESS="-rFnXM"
export TERM="xterm-256color"

#PATH
export PATH=~/hub/bin:$PATH

# Aliases
source ~/.aliases
source ~/.nq_aliases

# Font maps
for file in ~/.local/share/fonts/*.sh; do
    source "$file"
done

# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Theme
#ZSH_THEME="custom"
source ~/.zsh-powerlevel9k
ZSH_THEME="powerlevel9k/powerlevel9k"

# Plugins
plugins=(zsh-navigation-tools zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

# autocompletion files
fpath=(~/.zsh/completions $fpath)
autoload -U compinit && compinit

# kubectl autocompletion
source <(kubectl completion zsh)

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="~/.sdkman"
[[ -s "~/.sdkman/bin/sdkman-init.sh" ]] && source "~/.sdkman/bin/sdkman-init.sh"
