# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# User configuration
export LESS="-rFnXM"
export TERM="xterm-256color"

# Brew
eval $(/opt/homebrew/bin/brew shellenv)

# Aliases
source ~/.aliases
source ~/.nq_aliases

# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Theme
ZSH_THEME="powerlevel10k/powerlevel10k"
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Plugins
plugins=(zsh-navigation-tools zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

# autocompletion files
FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
autoload -U compinit && compinit


#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# Pyenv initialization
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

# Shell lang
if [[ -z "$LC_ALL" ]]; then
  export LC_ALL='en_US.UTF-8'
  export LANG='en_US.UTF-8'
fi
