---
- hosts: localhost
  vars_files:
    - vars.yml
    - vars.macos.yml
  tasks:
    - import_tasks: dmg.yml appName={{ item.name }} dmgURL={{ item.url }} fileType={{ item.type }}
      loop: "{{ dmg }}"
    - import_tasks: tap.yml
    - import_tasks: brew.yml
    - import_tasks: cask.yml
    - import_tasks: binary.yml
    - import_tasks: manual.yml
    - import_tasks: cargo.yml
    - import_tasks: pip.yml
    - import_tasks: go.yml
    - import_tasks: npm.yml
    - import_tasks: gem.yml
    #- import_tasks: jenv.yml
    #- import_tasks: bpkg.yml
