---
- name: Create apps directory
  file:
    path: "{{ home }}/apps"
    state: directory
- name: Check .tar.gz already at latest
  stat:
    path: "{{ home }}/apps/{{ item.original_dir }}"
  loop:  "{{ folder }}"
  register: check_targz_status
- name: Download .tar.gz files
  get_url: url={{ item.item.url }} dest=/tmp validate_certs=no
  with_items: "{{ check_targz_status.results }}"
  when: not item.stat.exists or item.item.force_reinstall|default (false)
  register: downloads
- name: Extract .tar.gz files
  unarchive: src={{ item.dest }} dest={{ home }}/apps
  loop: "{{ downloads.results }}"
  when: not item.skipped|default (false)
- name: Symlink extracted folders
  become: yes
  file: path=/opt/{{ item.item.item.symlinked_dir }} src={{ home }}/apps/{{ item.item.item.original_dir }} state=link
  loop: "{{ downloads.results }}"
