---
- name: Pacman update cache & upgrade
  become: yes
  pacman:
    update_cache: yes
    upgrade: yes
- name: Install pacman packages # Add --needed flag when possible to avoid reinstall already present packages
  become: yes
  pacman:
    name: "{{ pacman }}"
