---
#- name: Install snap packages
#  become: yes
#  snap:
#    name: "{{ snap }}"
#- name: Install snap packages (classic)
#  become: yes
#  with_dict: "{{ snap-classic }}"
#  snap:
#    name: "{{ item.value }}"
#    classic: yes
- name: Install snap packages
  become: yes
  loop: "{{ snap }}"
  shell:  "snap install {{ item }}"
- name: Install snap packages (classic)
  become: yes
  loop: "{{ snapclassic }}"
  shell:  "snap install {{ item }} --classic"
